[package]
name = "day12b"
version = "0.1.0"
authors = ["timvisee <tim@visee.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1"
rayon = "1.2"
regex = "1"
