[package]
name = "day07b"
version = "0.1.0"
authors = ["timvisee <tim@visee.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
